### ISSUE TITLE
metrics-reporter-librato-1.2.1-SNAPSHOT.jar Configuration

### ISSUE THREAD

**Issue by Arikius** [Graylog2/graylog-plugin-metrics-reporter#2]
Compiled via Maven and got the Jar
metrics-reporter-librato-1.2.1-SNAPSHOT.jar

However - when graylog2 loads we are seeing the following message 

2016-05-24T19:22:27.834+08:00 INFO  [CmdLineTool] Loaded plugins: [Anonymous Usage Statistics 2.0.0 [org.graylog.plugins.usagestatistics.UsageStatsPlugin], Pipeline Processor Plugin 1.0.0-beta.2 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin], Collector 1.0.0 [org.graylog.plugins.collector.CollectorPlugin], MapWidgetPlugin 1.0.0 [org.graylog.plugins.map.MapWidgetPlugin], Enterprise Integration Plugin 1.0.0 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin], Internal Metrics Librato Reporter 1.2.0 [org.graylog.plugins.metrics.librato.MetricsLibratoReporterPlugin]]
2016-05-24T19:22:27.855+08:00 ERROR [CmdLineTool] Invalid configuration
com.github.joschi.jadconfig.ParameterException: Required parameter "metrics_librato_username" not found.
        at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:127) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:99) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.processConfiguration(CmdLineTool.java:351) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.readConfiguration(CmdLineTool.java:344) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:177) [graylog.jar:?]
        at org.graylog2.bootstrap.Main.main(Main.java:44) [graylog.jar:?]

I Understand there should be a configuration (file?) - where do we configure it ? as after this error the graylog will not load unless deleting the plugin from the plugins dir

Thanks

**Comment by joschi** [comment]
@Arikius Simply add the required configuration settings like `metrics_librato_username` and `metrics_librato_token` to your Graylog configuration file and restart Graylog.

Also see [metrics-reporter-librato/README.md](https://github.com/Graylog2/graylog-plugin-metrics-reporter/blob/1.2.0/metrics-reporter-librato/README.md)
